string command
string error_message        # 错误消息回复： Can't catch current robot status
string charge_state
string chargepile_id
string current_floor
string current_pose_theta
string current_pose_x
string current_pose_y
string error_code
string estop_state
string extradata       # extraData 不符合数据命名，修改为小写d
string hand_charge
string hard_estop_abolish_state
string hard_estop_state
string is_paused
string move_retry_times
string move_status
string move_target
string power_percent
string running_status
string soft_estop_state
string target_floor
string task_id
string ts
string status               # 错误消息回复： UNKNOWN_ERROR
string type
string uuid
int32 count                 # 计数