uint16[] left_blink      # 左眨眼
uint16[] left_smile      # 左微笑
uint16[] left_eye_erect  # 左眼竖
uint16[] left_eye_level  # 左眼平
uint16[] left_eyebrow    # 左眉毛

uint16[] right_blink     # 右眨眼
uint16[] right_smile     # 右微笑
uint16[] right_eye_erect # 右眼竖
uint16[] right_eye_level # 右眼平
uint16[] right_eyebrow   # 右眉毛

uint16[] head_dian # 点头
uint16[] head_yao  # 摇头
uint16[] head_bai  # 摆头

uint16[] mouth # 嘴巴

